# Generated by Django 3.2.12 on 2022-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('return_date', models.DateField(null=True)),
            ],
        ),
    ]
