# Generated by Django 3.2.5 on 2021-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20210717_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(upload_to='www/media/hero'),
        ),
    ]
