# Generated by Django 3.2.5 on 2021-07-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0004_product_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
