# Generated by Django 3.2.5 on 2021-08-08 17:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_auto_20210728_0730'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
